# Allow anyone who has been /op'ed to bypass all permission checks
# (effectively making them have the same control as console)
ops-bypass-permissions: true

# The translation file you wish to use. (Default: messages.en_us.yml)
translation-file: "messages.en_us.yml"

worth-file: "worth.yml"
allow-selling: true

# Amount of time before being put into AFK mode (in seconds)
afk-timeout: 300

# Print debug statements to the console
debug: false

#The name of the server StickyCommands is running on
server: "lobby"

database:
  host: localhost
  port: 3306
  name: dbname
  username: root
  password: root
  table-prefix: stickycommands_
  # Maximum number of times mysql will try to reconnect before giving up.
  max-reconnects: 5
  # Use SSL?
  use-ssl: false