general:
  # Allow anyone who has been /op'ed to bypass all permission checks
  # (effectively making them have the same control as console)
  opsBypassPermissions: true
  # The translation file you wish to use. (Default: messages.en_us.yml)
  translationFile: "messages.en_us.yml"
  worthFile: "worth.yml"
  allowSelling: true

database:
  host: localhost
  port: 3306
  name: dbname
  username: root
  password: root
  # Maximum number of times mysql will try to reconnect before giving up.
  maxReconnects: 5
  # Use SSL?
  useSSL: false