name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        version: ["11"]
    container:
      image: jcxldn/openjdk-alpine:${{matrix.version}}-jdk
    steps:
    - uses: actions/checkout@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Setup gradle.properties
      run: |
        mkdir -p ~/.gradle/
        echo "::set-env name=GRADLE_USER_HOME::$HOME/.gradle"
        echo "ghUser=${GITHUB_ACTOR}" >> ~/.gradle/gradle.properties
        echo "ghUser=${GITHUB_TOKEN}" >> ~/.gradle/gradle.properties
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build with Gradle
      run: ./gradlew build
    - name: Save build artifact
      uses: actions/upload-artifact@v2
      with:
        name: java-${{matrix.version}}
        path: build/libs/*